
POST http://localhost:9001/komi-inbound/xml/service HTTP/1.1
Content-Type: application/application/xml

<!--  pacs.008 - example request for account enquiry from INDOIDJA into CI Hub (BIFASTJK)  -->
<ns:BusMsg xmlns:ns="urn:iso" xmlns:ns1="urn:iso:std:iso:20022:tech:xsd:head.001.001.01" xmlns:ns2="urn:iso:std:iso:20022:tech:xsd:pacs.008.001.08" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:iso ../../../xsd/phase1/MainCIHub.xsd ">
<ns:AppHdr>
<ns1:Fr>
<ns1:FIId>
<ns1:FinInstnId>
<ns1:Othr>
<ns1:Id>INDOIDJA</ns1:Id>
<!--  Sending system  -->
</ns1:Othr>
</ns1:FinInstnId>
</ns1:FIId>
</ns1:Fr>
<ns1:To>
<ns1:FIId>
<ns1:FinInstnId>
<ns1:Othr>
<ns1:Id>FASTIDJA</ns1:Id>
<!--  Receiving system  -->
</ns1:Othr>
</ns1:FinInstnId>
</ns1:FIId>
</ns1:To>
<ns1:BizMsgIdr>20210301INDOIDJA510ORB12345678</ns1:BizMsgIdr>
<!--  YYYY=Year (year e.g. 2021) MM=Month (month 01-12) DD=Day of month (e.g. 01-31) BBBBBBBBBBB=??? Bank identifier BBBBBBBB = First 8 characters of BIC code) XXX=Transaction Type identifier (e.g. 010=CT, 510=P2P CT, 500=AE, etc.) O=Originator (1 alphanumeric) CC=Channel (2 alphanumeric) SSSSSSSS=running serial number increases between 00000000 to 99999999  -->
<ns1:MsgDefIdr>pacs.008.001.08</ns1:MsgDefIdr>
<ns1:CreDt>2021-03-01T12:00:00Z</ns1:CreDt>
<!--  See CI Hub Guide p159 - this &lt;Sgntr&gt; stanza and its contents are dynamically added by ICE-XS when it signs a message going out - and removed when it verifies a message coming in  -->
<!--  <ns1:Sgntr>...</ns1:Sgntr>  -->
</ns:AppHdr>
<ns:Document>
<ns:FIToFICstmrCdtTrf>
<ns2:GrpHdr>
<ns2:MsgId>20210301INDOIDJA51012345678</ns2:MsgId>
<!--  YYYYMMDDBBBBBBBBBTTTSSSSSSSS  -->
<ns2:CreDtTm>2021-03-01T19:00:00.000</ns2:CreDtTm>
<ns2:NbOfTxs>1</ns2:NbOfTxs>
<ns2:SttlmInf>
<ns2:SttlmMtd>CLRG</ns2:SttlmMtd>
</ns2:SttlmInf>
</ns2:GrpHdr>
<ns2:CdtTrfTxInf>
<ns2:PmtId>
<ns2:EndToEndId>20210301INDOIDJA510ORB12345678</ns2:EndToEndId>
<!--  Same as BizMsgIdr when this is a request constructed by sender. If this message is a response to a previously sent message, this will be same as EndToEndId of the request message to which it is a response  -->
<ns2:TxId>20210301INDOIDJA11012345678</ns2:TxId>
</ns2:PmtId>
<!--  PmtTpinf/CtgyPurp not needed for Account Enquiry  -->
<ns2:IntrBkSttlmAmt Ccy="IDR">1234.56</ns2:IntrBkSttlmAmt>
<ns2:ChrgBr>DEBT</ns2:ChrgBr>
<ns2:Dbtr/>
<!--  empty Dbtr tag, required by XSD  -->
<!--  /FIToFICstmrCdtTrf/CdtTrfTxInf/Dbtr/Nm not required for AE  -->
<!--  /FIToFICstmrCdtTrf/CdtTrfTxInf/Dbtr/Id not required for AE  -->
<!--  /FIToFICstmrCdtTrf/CdtTrfTxInf/DbtrAcct not required for AE  -->
<ns2:DbtrAgt>
<ns2:FinInstnId>
<ns2:Othr>
<ns2:Id>INDOIDJA</ns2:Id>
<!--  Debiting Agent Bank ID  -->
</ns2:Othr>
</ns2:FinInstnId>
</ns2:DbtrAgt>
<ns2:CdtrAgt>
<ns2:FinInstnId>
<ns2:Othr>
<ns2:Id>CENAIDJA</ns2:Id>
<!--  Crediting Agent Bank ID  -->
</ns2:Othr>
</ns2:FinInstnId>
</ns2:CdtrAgt>
<!--  Cdtr info not needed for AE, but Cdtr tag must be present for XSD validation  -->
<ns2:Cdtr/>
<ns2:CdtrAcct>
<ns2:Id>
<ns2:Othr>
<ns2:Id>987654321</ns2:Id>
<!--  Crediting Account Number - needed for AE  -->
</ns2:Othr>
</ns2:Id>
<!--  /Tp Creditor account type, not needed for AE  -->
</ns2:CdtrAcct>
<!--  No SplmtryData needed for AE  -->
</ns2:CdtTrfTxInf>
</ns:FIToFICstmrCdtTrf>
</ns:Document>
</ns:BusMsg>