POST http://localhost:9001/services/api/enquiry HTTP/1.1
Content-Type: application/json

{
    "MessageRequest": {
        "msgType": "Settlement",
        "endToEndId": "20210914MNDRIDJA019O0300000018"
    }
}